# conda env create -f environment.yml
name: b2f
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6
  - owslib
  # ng
  - beautifulsoup4
  - shapely
  - jsonpath-ng
  - click
  - pandas
  - tqdm
  - colander
  # tests
  - pytest
  - flake8
